inherit_from:
  - https://bitbucket.org/bsm/misc/raw/master/rubocop/default.yml

AllCops:
  TargetRubyVersion: "2.2"

Style/ClassVars:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Naming/FileName:
  Enabled: false
